# for k8s versions before 1.9.0 use apps/v1beta2 and before 1.8.0 use extensions/v1beta1
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: pipeline
spec:
  selector:
    matchLabels:
      app: jenkins-app
      env: dev
  replicas: 2
  template:
    metadata:
      labels:
        app: jenkins-app
        env: dev
    spec:
      containers:
      - name: jenkins-app
        image: shegoj/hrapp:v3     # pod creation using image: jenkins
        command:
          - "your"
          - "custom"
          - "command"
        ports:
        - containerPort: 80

# Service Management For Port-Forwarding.
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service-clusterip
  namespace: hr
spec:
  selector:
    app: jenkins-app
    env: dev
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP

# Creating Application LoadBalancer Endpoint.
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service-loadbalancer
  namespace: hr
spec:
  selector:
    app: jenkins-app
    env: dev
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

#  kubectl apply -f jenkins-deployment.yaml