
# Creating cluster Configuration
----
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: My-Kits
  region: eu-west-1

nodeGroups:
  - name: nodegroup-1
    instanceType: t2.small
    desiredCapacity: 2
    ssh:
      publicKeyName: Kitskat2023

# eksctl create cluster -f cluster.yaml